[project]
name = "allison"
version = "0.1.0"
description = "A Machine Learning library for begainers"
authors = [
  {name = "Mitchell Mirano", email = "mitchellmirano25@gmail.com"},
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.2",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.3",
    "pytest>=8.4.1",
    "seaborn>=0.13.2",
]
